name: Debian Package 

on:
    release:
       types: [created] # 表示在创建新的 Release 时触发  

jobs:
  debian:
    name: Debian/Ubuntu
    strategy:
      fail-fast: false
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Build
        run: |
          bash build.sh 
          
      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          name: debian
          path: ./*.deb
